let a = 10;
let b = 20;
var linebreak = "<br>";
result = (a == b);
document.write(result);
document.write(linebreak);
result = (a < b);
document.write(result);
document.write(linebreak);
result = (a > b);
document.write(result);
document.write(linebreak);
result = (a != b);
document.write(result);
document.write(linebreak);
result = (a <= b);
document.write(result);
document.write(linebreak);
result = (a >= b);
document.write(result);
document.write(linebreak);